services:
  postgres:
    image: postgres:18
    container_name: ssubench-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  flyway:
    depends_on:
      postgres:
        condition: service_healthy
    image: flyway/flyway
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/migration:/flyway/sql
    command: migrate

volumes:
  postgres_data: